name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv==0.4.20
      - name: Sync deps
        run: uv sync --all-extras
      - name: Lint
        run: uv run ruff check . && uv run black --check . && uv run mypy .
      - name: Tests
        run: uv run pytest -q
