name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv==0.4.20

      - name: Sync dependencies (main + dev extra)
        run: uv sync --extra dev

      - name: Diagnose environment
        run: |
          uv run python -V
          uv run python -c "import sys,platform;print(platform.platform());print(sys.executable)"
          uv run python -c "import pandas,numpy,matplotlib,plotly,yfinance; print('Imports OK')"

      - name: Ruff
        run: uv run ruff check .

      - name: Black
        run: uv run black --check .

      - name: Mypy
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest -q
